name: Vue Notifier

on:
  push:
    branches:
      - main
    paths:
      - '**/*.vue'

jobs:
  vue_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Get the PR Number
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=#)\d+')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Get the PR Title
        run: |
          PR_TITLE=$(echo "${{ github.event.head_commit.message }}" | tail -n 1)
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Vueファイルに変更がありました",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Vueファイルに変更がありました\n*<https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER}}|#${{ env.PR_NUMBER }} ${{ env.PR_TITLE }}>*"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.VUE_NOTIFIER_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
