name: Vue Notifier

on:
  push:
    branches:
      - main
    paths:
      - '**/*.vue'

jobs:
  vue_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Get the PR Link
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=#)\d+' || true)
          PR_TITLE=$(echo "${{ github.event.head_commit.message }}" | tail -n 1)
          SHORT_COMMIT_ID=$(echo "${{ github.event.head_commit.id }}" | cut -c 1-7)
          if [ -z "$PR_NUMBER" ]; then
            PR_LINK=<https://github.com/${{ github.repository }}/commit/${{ github.event.head_commit.id }}|#$SHORT_COMMIT_ID $PR_TITLE>
          else
            PR_LINK=<https://github.com/${{ github.repository }}/pull/$PR_NUMBER|#$PR_NUMBER $PR_TITLE>
          fi
          echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV
          echo "${{ github.event.head_commit }}"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Vueファイルに変更がありました",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Vueファイルに変更がありました\n*${{ env.PR_LINK }}*"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.VUE_NOTIFIER_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
