name: Deploy Staging

on:
  push:
    branches:
      - main
    paths:
      - '**/*.vue'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the PR that triggered the push
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=#)\d+')
          echo "$PR_NUMBER"
