name: Deploy Staging

on:
  push:
    branches:
      - main
    paths:
      - '**/*.vue'

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://example.com
    steps:
      - name: Get the PR that triggered the push
        run: echo "$GITHUB_EVENT_PATH"
